mtmoney.seguranca.enable-https=true

#spring.jpa.database=
spring.datasource.url={DATABASE_URL}
spring.datasource.username={DATABASE_USERNAME}
spring.datasource.password={DATABASE_PASSWORD}

mtmoney.origin-permitida=https://mtmoneyui.herokuapp.com